# .kodiak.toml
# Minimal config. version is the only required field.
version = 1
auto_approve_usernames = ["yowainwright"]
merge.automerge_label = ['codependencies','automerge ğŸš€']
update.autoupdate_label = 'autoupdate ğŸ”'
